# Generated by Django 5.0.3 on 2024-05-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('skills', models.CharField(max_length=200)),
                ('responsibilities', models.TextField()),
                ('experience', models.CharField(max_length=100)),
                ('educational_requirements', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
