# Generated by Django 5.0.3 on 2024-05-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_joblisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
