# Generated by Django 5.0.3 on 2024-05-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured_alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for the featured image, used for SEO and accessibility.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload an image to feature for this category.', null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='featured_title',
            field=models.CharField(blank=True, help_text='Title for the featured image, used for SEO and accessibility.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the category.', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier for the category.', unique=True),
        ),
    ]
