# Generated by Django 5.0.3 on 2024-05-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
